### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by bwinton** [Osmose/atom-whimsy#2]
[Enter steps to reproduce below:]
1. Split Left
2. Close the newly-created right-hand pane.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-whimsy](https://github.com/Osmose/atom-whimsy) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'style' of null

```
At /Users/bwinton/Programming/atom/atom-whimsy/lib/atom-whimsy.js:29

TypeError: Cannot read property 'style' of null
  at /Users/bwinton/Programming/atom/atom-whimsy/lib/atom-whimsy.js:29:55
  at Emitter.module.exports.Emitter.emit (/Applications/Local/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didDestroyPaneItem (/Applications/Local/Atom.app/Contents/Resources/app.asar/src/pane-container.js:311:27)
  at Pane.module.exports.Pane.removeItem (/Applications/Local/Atom.app/Contents/Resources/app.asar/src/pane.js:386:17)
  at Pane.module.exports.Pane.destroyItem (/Applications/Local/Atom.app/Contents/Resources/app.asar/src/pane.js:442:16)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Local/Atom.app/Contents/Resources/app.asar/src/pane.js:419:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Local/Atom.app/Contents/Resources/app.asar/src/workspace.js:600:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Local/Atom.app/Contents/Resources/app.asar/src/workspace.js:639:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Local/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:308:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Local/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Local/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Local/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Local/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Local/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -0:26.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:24.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:24.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  7x -0:22.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.9.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "speedkills"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-whimsy, v0.1.1
emmet, v2.3.12
linter, v1.1.0
linter-csslint, v0.0.14
linter-eslint, v1.0.11
linter-less, v2.0.3
linter-pep8, v0.2.0
minimap, v4.10.1

# Dev
No dev packages
```

**Comment by Osmose** [comment]
Fixed in https://github.com/Osmose/atom-whimsy/commit/a8ec28095da3af0b5401ceebbc3035934ac8ccc3.
